//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingService.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAnswers
    {
        public int UsersTestId { get; set; }
        public int QuestionId { get; set; }
        public System.DateTime BeginningTime { get; set; }
        public Nullable<System.DateTime> EndingTime { get; set; }
        public string AnswerStructure { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual UsersTests UsersTests { get; set; }
    }
}
